### ISSUE TITLE
Docker Compose V2

### ISSUE THREAD

**Issue by Pipboyguy** [pathwaycom/pathway-benchmarks#1]
`docker-compose: not found` on V2 (which is `docker compose`)

**Comment by pw-ppodhajski** [comment]
Thank you - we have prepared a fix, it will be merged in several days.

**Comment by pw-ppodhajski** [comment]
Resolved in [11b355a](https://github.com/pathwaycom/pathway-benchmarks/commit/11b355af82a811eea13e0d77da41348a425d26e6), thank you once again for reporting the issue.
